networks:
  mcpuntappd:
    driver: bridge

services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite
    hostname: azurite
    restart: always
    command: "azurite --blobHost 0.0.0.0 --blobPort 10000 --queueHost 0.0.0.0 --queuePort 10001 --tableHost 0.0.0.0 --tablePort 10002"
    volumes:
      - ../azurite/data:/data
    networks:
      - mcpuntappd
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"

  mcpuntappd:
    image: mcr.microsoft.com/devcontainers/dotnet:9.0
    container_name: mcpuntappd
    hostname: mcpuntappd
    command: sleep infinity
    environment:
      DOTNET_EnableWriteXorExecute: 0
    networks:
      - mcpuntappd
    depends_on:
      - azurite
    volumes:
      - ..:/workspaces:cached